#!/bin/bash

echo "=== Testing Jewelry Reorder API ==="
echo ""

# Configuration
API_URL="https://api.celorajewelry.com/api"
TOKEN="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NWNkNWFkMjE2OWQwMzI1MTllZWIzZiIsInJvbGUiOiI2ODVjZGMwYzExMDNmM2M4ODI4OTEwOGUiLCJyb2xlTmFtZSI6IlNVUEVSQURNSU4iLCJwZXJtaXNzaW9ucyI6W3sicmVzb3VyY2UiOiJkYXNoYm9hcmQiLCJhY3Rpb25zIjpbImNyZWF0ZSIsInJlYWQiLCJ1cGRhdGUiLCJkZWxldGUiXSwiX2lkIjoiNjhjM2M1MGUxOTdjNzFiOWE3Y2I4ZTgzIiwic291cmNlIjoicm9sZSJ9LHsicmVzb3VyY2UiOiJvcmRlcm1hbmFnZW1lbnQiLCJhY3Rpb25zIjpbImNyZWF0ZSIsInJlYWQiLCJ1cGRhdGUiLCJkZWxldGUiXSwiX2lkIjoiNjhjM2M1MGUxOTdjNzFiOWE3Y2I4ZTg0Iiwic291cmNlIjoicm9sZSJ9LHsicmVzb3VyY2UiOiJzaGFwZSIsImFjdGlvbnMiOlsiY3JlYXRlIiwicmVhZCIsInVwZGF0ZSIsImRlbGV0ZSJdLCJfaWQiOiI2OGMzYzUwZTE5N2M3MWI5YTdjYjhlODUiLCJzb3VyY2UiOiJyb2xlIn0seyJyZXNvdXJjZSI6ImRpYW1vbmRzIiwiYWN0aW9ucyI6WyJjcmVhdGUiLCJyZWFkIiwidXBkYXRlIiwiZGVsZXRlIl0sIl9pZCI6IjY4YzNjNTBlMTk3YzcxYjlhN2NiOGU4NiIsInNvdXJjZSI6InJvbGUifSx7InJlc291cmNlIjoiaGVsZGRpYW1vbmRzIiwiYWN0aW9ucyI6WyJjcmVhdGUiLCJyZWFkIiwidXBkYXRlIiwiZGVsZXRlIl0sIl9pZCI6IjY4YzNjNTBlMTk3YzcxYjlhN2NiOGU4NyIsInNvdXJjZSI6InJvbGUifSx7InJlc291cmNlIjoicHJpY2VtYW5hZ2VtZW50IiwiYWN0aW9ucyI6WyJjcmVhdGUiLCJyZWFkIiwidXBkYXRlIiwiZGVsZXRlIl0sIl9pZCI6IjY4YzNjNTBlMTk3YzcxYjlhN2NiOGU4OCIsInNvdXJjZSI6InJvbGUifSx7InJlc291cmNlIjoiamV3ZWxyeXN0eWxlIiwiYWN0aW9ucyI6WyJjcmVhdGUiLCJyZWFkIiwidXBkYXRlIiwiZGVsZXRlIl0sIl9pZCI6IjY4YzNjNTBlMTk3YzcxYjlhN2NiOGU4OSIsInNvdXJjZSI6InJvbGUifSx7InJlc291cmNlIjoiYWRkamV3ZWxyeSIsImFjdGlvbnMiOlsiY3JlYXRlIiwicmVhZCIsInVwZGF0ZSIsImRlbGV0ZSJdLCJfaWQiOiI2OGMzYzUwZTE5N2M3MWI5YTdjYjhlOGEiLCJzb3VyY2UiOiJyb2xlIn0seyJyZXNvdXJjZSI6Impld2VsZXJpZXMiLCJhY3Rpb25zIjpbImNyZWF0ZSIsInJlYWQiLCJ1cGRhdGUiLCJkZWxldGUiXSwiX2lkIjoiNjhjM2M1MGUxOTdjNzFiOWE3Y2I4ZThiIiwic291cmNlIjoicm9sZSJ9LHsicmVzb3VyY2UiOiJoaWdobGlnaHRwcm9kdWN0cyIsImFjdGlvbnMiOlsiY3JlYXRlIiwicmVhZCIsInVwZGF0ZSIsImRlbGV0ZSJdLCJfaWQiOiI2OGMzYzUwZTE5N2M3MWI5YTdjYjhlOGMiLCJzb3VyY2UiOiJyb2xlIn0seyJyZXNvdXJjZSI6InZlbmRvcnMiLCJhY3Rpb25zIjpbImNyZWF0ZSIsInJlYWQiLCJ1cGRhdGUiLCJkZWxldGUiXSwiX2lkIjoiNjhjM2M1MGUxOTdjNzFiOWE3Y2I4ZThkIiwic291cmNlIjoicm9sZSJ9LHsicmVzb3VyY2UiOiJreWMiLCJhY3Rpb25zIjpbImNyZWF0ZSIsInJlYWQiLCJ1cGRhdGUiLCJkZWxldGUiXSwiX2lkIjoiNjhjM2M1MGUxOTdjNzFiOWE3Y2I4ZThlIiwic291cmNlIjoicm9sZSJ9LHsicmVzb3VyY2UiOiJjYXRlZ29yeSIsImFjdGlvbnMiOlsiY3JlYXRlIiwicmVhZCIsInVwZGF0ZSIsImRlbGV0ZSJdLCJfaWQiOiI2OGMzYzUwZTE5N2M3MWI5YTdjYjhlOGYiLCJzb3VyY2UiOiJyb2xlIn0seyJyZXNvdXJjZSI6InN1YmNhdGVnb3J5IiwiYWN0aW9ucyI6WyJjcmVhdGUiLCJyZWFkIiwidXBkYXRlIiwiZGVsZXRlIl0sIl9pZCI6IjY4YzNjNTBlMTk3YzcxYjlhN2NiOGU5MCIsInNvdXJjZSI6InJvbGUifSx7InJlc291cmNlIjoiZmFxcyIsImFjdGlvbnMiOlsiY3JlYXRlIiwicmVhZCIsInVwZGF0ZSIsImRlbGV0ZSJdLCJfaWQiOiI2OGMzYzUwZTE5N2M3MWI5YTdjYjhlOTEiLCJzb3VyY2UiOiJyb2xlIn0seyJyZXNvdXJjZSI6ImlucXVpcnkiLCJhY3Rpb25zIjpbImNyZWF0ZSIsInJlYWQiLCJ1cGRhdGUiLCJkZWxldGUiXSwiX2lkIjoiNjhjM2M1MGUxOTdjNzFiOWE3Y2I4ZTkyIiwic291cmNlIjoicm9sZSJ9LHsicmVzb3VyY2UiOiJhZGRiYW5uZXJzIiwiYWN0aW9ucyI6WyJjcmVhdGUiLCJyZWFkIiwidXBkYXRlIiwiZGVsZXRlIl0sIl9pZCI6IjY4YzNjNTBlMTk3YzcxYjlhN2NiOGU5MyIsInNvdXJjZSI6InJvbGUifSx7InJlc291cmNlIjoicmV0YWlsZXIiLCJhY3Rpb25zIjpbImNyZWF0ZSIsInJlYWQiLCJ1cGRhdGUiLCJkZWxldGUiXSwiX2lkIjoiNjhjM2M1MGUxOTdjNzFiOWE3Y2I4ZTk0Iiwic291cmNlIjoicm9sZSJ9LHsicmVzb3VyY2UiOiJjb3Vwb25zIiwiYWN0aW9ucyI6WyJjcmVhdGUiLCJyZWFkIiwidXBkYXRlIiwiZGVsZXRlIl0sIl9pZCI6IjY4YzNjNTBlMTk3YzcxYjlhN2NiOGU5NSIsInNvdXJjZSI6InJvbGUifSx7InJlc291cmNlIjoiZnVsbC1kaXNjb3VudCIsImFjdGlvbnMiOlsiY3JlYXRlIiwicmVhZCIsInVwZGF0ZSIsImRlbGV0ZSJdLCJfaWQiOiI2OGMzYzUwZTE5N2M3MWI5YTdjYjhlOTYiLCJzb3VyY2UiOiJyb2xlIn0seyJyZXNvdXJjZSI6InRvcC1oZWFkZXItaW50cm8iLCJhY3Rpb25zIjpbImNyZWF0ZSIsInJlYWQiLCJ1cGRhdGUiLCJkZWxldGUiXSwiX2lkIjoiNjhjM2M1MGUxOTdjNzFiOWE3Y2I4ZTk3Iiwic291cmNlIjoicm9sZSJ9LHsicmVzb3VyY2UiOiJpbnRyby1wb3B1cCIsImFjdGlvbnMiOlsiY3JlYXRlIiwicmVhZCIsInVwZGF0ZSIsImRlbGV0ZSJdLCJfaWQiOiI2OGMzYzUwZTE5N2M3MWI5YTdjYjhlOTgiLCJzb3VyY2UiOiJyb2xlIn0seyJyZXNvdXJjZSI6InByb21vdGlvbmFsLXN0cmlwZSIsImFjdGlvbnMiOlsiY3JlYXRlIiwicmVhZCIsInVwZGF0ZSIsImRlbGV0ZSJdLCJfaWQiOiI2OGMzYzUwZTE5N2M3MWI5YTdjYjhlOTkiLCJzb3VyY2UiOiJyb2xlIn0seyJyZXNvdXJjZSI6ImNhcmF0LXNpemUiLCJhY3Rpb25zIjpbImNyZWF0ZSIsInJlYWQiLCJ1cGRhdGUiLCJkZWxldGUiXSwiX2lkIjoiNjhjM2M1MGUxOTdjNzFiOWE3Y2I4ZTlhIiwic291cmNlIjoicm9sZSJ9LHsicmVzb3VyY2UiOiJzdWJzY3JpYmVycyIsImFjdGlvbnMiOlsiY3JlYXRlIiwicmVhZCIsInVwZGF0ZSIsImRlbGV0ZSJdLCJfaWQiOiI2OGMzYzUwZTE5N2M3MWI5YTdjYjhlOWIiLCJzb3VyY2UiOiJyb2xlIn0seyJyZXNvdXJjZSI6InVzZXItbGlzdCIsImFjdGlvbnMiOlsiY3JlYXRlIiwicmVhZCIsInVwZGF0ZSIsImRlbGV0ZSJdLCJfaWQiOiI2OGMzYzUwZTE5N2M3MWI5YTdjYjhlOWMiLCJzb3VyY2UiOiJyb2xlIn0seyJyZXNvdXJjZSI6InBhY2thZ2luZyIsImFjdGlvbnMiOlsiY3JlYXRlIiwicmVhZCIsInVwZGF0ZSIsImRlbGV0ZSJdLCJfaWQiOiI2OGMzYzUwZTE5N2M3MWI5YTdjYjhlOWQiLCJzb3VyY2UiOiJyb2xlIn0seyJyZXNvdXJjZSI6InNvY2lhbHBvc3QiLCJhY3Rpb25zIjpbImNyZWF0ZSIsInJlYWQiLCJ1cGRhdGUiLCJkZWxldGUiXSwiX2lkIjoiNjhjM2M1MGUxOTdjNzFiOWE3Y2I4ZTllIiwic291cmNlIjoicm9sZSJ9LHsicmVzb3VyY2UiOiJ2aXJ0dWFsLWFwcG9pbnRtZW50IiwiYWN0aW9ucyI6WyJjcmVhdGUiLCJyZWFkIiwidXBkYXRlIiwiZGVsZXRlIl0sIl9pZCI6IjY4YzNjNTBlMTk3YzcxYjlhN2NiOGU5ZiIsInNvdXJjZSI6InJvbGUifSx7InJlc291cmNlIjoiYWRkLWJsb2ciLCJhY3Rpb25zIjpbImNyZWF0ZSIsInJlYWQiLCJ1cGRhdGUiLCJkZWxldGUiXSwiX2lkIjoiNjhjM2M1MGUxOTdjNzFiOWE3Y2I4ZWEwIiwic291cmNlIjoicm9sZSJ9LHsicmVzb3VyY2UiOiJibG9nLWxpc3QiLCJhY3Rpb25zIjpbImNyZWF0ZSIsInVwZGF0ZSIsImRlbGV0ZSIsInJlYWQiXSwiX2lkIjoiNjhjM2M1MGUxOTdjNzFiOWE3Y2I4ZWExIiwic291cmNlIjoicm9sZSJ9LHsicmVzb3VyY2UiOiJ1c2VycyIsImFjdGlvbnMiOlsiY3JlYXRlIiwicmVhZCIsInVwZGF0ZSIsImRlbGV0ZSJdLCJfaWQiOiI2OGMzYzUwZTE5N2M3MWI5YTdjYjhlYTIiLCJzb3VyY2UiOiJyb2xlIn0seyJyZXNvdXJjZSI6InJvbGUmcGVybWlzc2lvbiIsImFjdGlvbnMiOlsiY3JlYXRlIiwicmVhZCIsInVwZGF0ZSIsImRlbGV0ZSJdLCJfaWQiOiI2OGMzYzUwZTE5N2M3MWI5YTdjYjhlYTMiLCJzb3VyY2UiOiJyb2xlIn0seyJyZXNvdXJjZSI6ImludHJvX2xpbmUiLCJhY3Rpb25zIjpbImNyZWF0ZSIsInJlYWQiLCJ1cGRhdGUiLCJkZWxldGUiXSwiX2lkIjoiNjk1Y2VmMjBlYTFmMGQ5OGRiMzM2MTQ1Iiwic291cmNlIjoicm9sZSJ9LHsicmVzb3VyY2UiOiJibG9nIiwiYWN0aW9ucyI6WyJjcmVhdGUiLCJyZWFkIiwidXBkYXRlIiwiZGVsZXRlIl0sIl9pZCI6IjY4YzNjNjMyMTk3YzcxYjlhN2NiOGY4NyIsInNvdXJjZSI6ImluZGl2aWR1YWwifSx7InJlc291cmNlIjoicHJvZHVjdCIsImFjdGlvbnMiOlsicmVhZCIsInVwZGF0ZSJdLCJfaWQiOiI2OGMzYzYzMjE5N2M3MWI5YTdjYjhmODgiLCJzb3VyY2UiOiJpbmRpdmlkdWFsIn0seyJyZXNvdXJjZSI6ImludmVudG9yeSIsImFjdGlvbnMiOlsicmVhZCJdLCJfaWQiOiI2OGMzYzYzMjE5N2M3MWI5YTdjYjhmODkiLCJzb3VyY2UiOiJpbmRpdmlkdWFsIn0seyJyZXNvdXJjZSI6InZlbmRvciIsImFjdGlvbnMiOlsiY3JlYXRlIiwiZGVsZXRlIl0sIl9pZCI6IjY4YzNjNjMyMTk3YzcxYjlhN2NiOGY4YSIsInNvdXJjZSI6ImluZGl2aWR1YWwifV0sInBlcm1pc3Npb25zU291cmNlIjoiY29tYmluZWQiLCJ0b2tlblZlcnNpb24iOjAsImlhdCI6MTc2NzY5ODIwOSwiZXhwIjoxNzY4MzAzMDA5fQ.0cON_WfIi5Eq26n1jHpAlm9XFaqFW3tc3o91xei8B3Y"

echo "Step 1: Fetch current Earrings order"
echo "--------------------------------------"
curl -s -X POST "$API_URL/jewelry/search" \
  -H 'Content-Type: application/json' \
  --data-raw '{
    "jewelryType": "Earrings",
    "sortBy": "sequence",
    "sortOrder": "asc"
  }' | jq -r '.data[] | "\(.sequence) - \(.title) (\(.jewelryId))"' | head -10

echo ""
echo "Step 2: Test reordering - Move item to first position"
echo "------------------------------------------------------"

# Get the third item's ID
THIRD_ITEM_ID=$(curl -s -X POST "$API_URL/jewelry/search" \
  -H 'Content-Type: application/json' \
  --data-raw '{
    "jewelryType": "Earrings",
    "sortBy": "sequence",
    "sortOrder": "asc",
    "limit": 3
  }' | jq -r '.data[2].jewelryId')

echo "Moving item: $THIRD_ITEM_ID to position 0"

curl -s -X PUT "$API_URL/jewelry/$THIRD_ITEM_ID" \
  -H 'Content-Type: application/json' \
  -H "Authorization: Bearer $TOKEN" \
  --data-raw '{"newIndex": 0}' | jq '{jewelryId, title, sequence, jewelryType}'

echo ""
echo "Step 3: Verify new order"
echo "------------------------"
sleep 1
curl -s -X POST "$API_URL/jewelry/search" \
  -H 'Content-Type: application/json' \
  --data-raw '{
    "jewelryType": "Earrings",
    "sortBy": "sequence",
    "sortOrder": "asc"
  }' | jq -r '.data[] | "\(.sequence) - \(.title) (\(.jewelryId))"' | head -10

echo ""
echo "=== Test Complete ==="
